### PR TITLE
WIP - Check DNS records via exec and dig command

### PR DESCRIPTION
**Pull request by vaidas-lungis**
Check DNS records via exec and dig command

issue https://github.com/hostinger/disposable-emails/issues/21

http://stackoverflow.com/a/3938155/2728507
http://stackoverflow.com/a/2368546/2728507

### CODE REVIEW

**Comment by tonyspa** [comment]
@vaidas-lungis any timeout settings?
```
       +time=T
           Sets the timeout for a query to T seconds. The default timeout is 5 seconds. An attempt to set T to less than 1 will result in a query timeout of 1
           second being applied.

       +tries=T
           Sets the number of times to try UDP queries to server to T instead of the default, 3. If T is less than or equal to zero, the number of tries is
           silently rounded up to 1.

       +retry=T
           Sets the number of times to retry UDP queries to server to T instead of the default, 2. Unlike +tries, this does not include the initial query.
```

**Comment by tonyspa** [comment]
lets try 🚀

**Comment by vaidas-lungis** [comment]
Later today

**Comment by vaidas-lungis** [comment]
Overriding default timeout (5sec) to 2 sec but did not change default `tries` value (3). So max time could be 2 * 3 = 6 sec for lookup.

**Pull request merged**
